### ISSUE TITLE
Kubecon?

### ISSUE THREAD

**Issue by condaatje** [andydunstall/piko#170]
Hey @andydunstall - it's a long shot, but by any chance are you going to Kubecon? We'd love to meet up, maybe get lunch or dinner on Hyperbolic!

I think we are your biggest fans, piko has been crushing it for us and we've been able to build a massively decentralized cloud architecture around it. Very keen to see what further work can be done together!

(cc @yquansah - we are both going!)

**Comment by andydunstall** [comment]
Hey @condaatje, no I'm not unfortunately :(

> I think we are your biggest fans, piko has been crushing it for us and we've been able to build a massively decentralized cloud architecture around it. Very keen to see what further work can be done together!

Thats great! Please let me know if theres any features or improvements you want me to add to Piko!

Based on our experience using Piko at DragonflyDB, the next improvements I was going to add are around how Piko handles server deployments at scale, such as:
- Connection rebalancing: If one node has far more upstreams than the other nodes, it can gradually shed connections until the nodes are more balanced. Such as if you add a new Piko node it should gradually take on upstreams from the other nodes. (It will be optional)
- Graceful shutdown: Instead of nodes immediately shedding all upstream connections when shutdown (which can cause ton of reconnects to the other nodes all at once), will gradually shed connections over a configured interval (Again will be optional)

**Comment by condaatje** [comment]
ah, too bad - maybe next year!

connection re-balancing sounds very cool, we would happily beta test that!

we are also considering accessing kube-apiserver of several sub-clusters via piko rather than tailscale operator, if we can match the existing security posture. we've got an interesting threat model in that these sub-clusters are run by third-parties wishing to rent out their nodes, and have no public IP.

Would love to keep the discussion going as it relates to multiparty cybersecurity! I think we can get pretty far with rbac and service accounts for the connection, but I'm sure there will be aspects of this area we can improve in our architecture as we get deeper into a piko-native p2p cloud setup!

**Comment by andydunstall** [comment]
Great, yep sure happy to discuss!

**Comment by andydunstall** [comment]
I'll close this issue for now, but feel free to open any issues you want to discuss!

**Comment by condaatje** [comment]
sounds good - was great to run into the dragonfly team at kubecon!
